# Generated by Django 4.2.16 on 2025-11-25 09:03

from django.db import migrations


def migrate_chats_to_sessions(apps, schema_editor):
    """
    Create a ChatSession for each user and assign their chats to it.
    """
    Chat = apps.get_model('chatbot', 'Chat')
    ChatSession = apps.get_model('chatbot', 'ChatSession')
    User = apps.get_model('auth', 'User')

    # Get all users who have chats with None session
    chats_without_session = Chat.objects.filter(session__isnull=True)

    if not chats_without_session.exists():
        return

    # Create one "Previous Chats" session per user
    for user in User.objects.all():
        session, created = ChatSession.objects.get_or_create(
            user=user,
            name='Previous Chats',
            defaults={'model': 'gemini-1.5-flash'}
        )
        # Assign all chats without a session to this user's session
        if created:
            Chat.objects.filter(session__isnull=True).update(session=session)


def reverse_migrate(apps, schema_editor):
    """Reverse the migration by removing sessions created during this migration."""
    ChatSession = apps.get_model('chatbot', 'ChatSession')

    # Find sessions that were created during this migration (named "Previous Chats")
    ChatSession.objects.filter(name='Previous Chats').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_alter_chat_options_remove_chat_user_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_chats_to_sessions, reverse_migrate),
    ]
