# Generated by Django 4.2.16 on 2025-12-01 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0004_alter_chatsession_model_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_instance_created', models.DateTimeField(blank=True, null=True)),
                ('next_instance_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance_number', models.IntegerField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instance', to='chatbot.task')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chatbot.recurringtasktemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_reminder_enabled', models.BooleanField(default=True)),
                ('reminder_days_before', models.IntegerField(default=1)),
                ('reminder_time', models.TimeField(default='09:00')),
                ('overdue_reminder_enabled', models.BooleanField(default=True)),
                ('daily_digest_enabled', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='08:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deadline_reminder', 'Deadline Reminder'), ('task_due_today', 'Task Due Today'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('recurring_created', 'Recurring Task Created')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chatbot.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_messages', models.IntegerField()),
                ('user_messages', models.IntegerField()),
                ('ai_responses', models.IntegerField()),
                ('total_sessions', models.IntegerField()),
                ('active_sessions', models.IntegerField()),
                ('avg_session_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TaskAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_tasks', models.IntegerField()),
                ('pending_count', models.IntegerField()),
                ('in_progress_count', models.IntegerField()),
                ('completed_count', models.IntegerField()),
                ('overdue_count', models.IntegerField()),
                ('completed_today', models.IntegerField()),
                ('completion_rate', models.FloatField()),
                ('urgent_count', models.IntegerField()),
                ('high_count', models.IntegerField()),
                ('medium_count', models.IntegerField()),
                ('low_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='chatbot_tas_user_id_9d1399_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='recurringtasktemplate',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_rec_user_id_12eaed_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtasktemplate',
            index=models.Index(fields=['user', 'next_instance_date'], name='chatbot_rec_user_id_ad4e36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recurringtaskinstance',
            unique_together={('template', 'task')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='chatbot_not_user_id_a80f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_sent'], name='chatbot_not_user_id_3c95b0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['user', '-date'], name='chatbot_cha_user_id_7d09f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatanalytics',
            unique_together={('user', 'date')},
        ),
    ]
