# Generated by Django 4.2.16 on 2025-12-07 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0005_recurringtasktemplate_recurringtaskinstance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaudeTerminalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terminal_pid",
                    models.IntegerField(
                        blank=True, help_text="Process ID of Claude terminal", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Terminal is running and connected"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Terminal mode enabled for this session",
                    ),
                ),
                (
                    "connection_method",
                    models.CharField(
                        choices=[
                            ("http", "HTTP Proxy"),
                            ("ipc", "Inter-Process Communication"),
                            ("file", "File Queue"),
                        ],
                        default="http",
                        help_text="Communication method (HTTP, IPC, or File)",
                        max_length=10,
                    ),
                ),
                (
                    "connection_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Connection config (port for HTTP, pipe path for IPC, queue dir for File)",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last error message if any"),
                ),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claude_terminals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "web_chat_session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminal_session",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claude Terminal Session",
                "verbose_name_plural": "Claude Terminal Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="chatbot_cla_user_id_2ac10f_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-updated_at"],
                        name="chatbot_cla_is_acti_c9deb4_idx",
                    ),
                ],
            },
        ),
    ]
