# Generated by Django 4.2.3 on 2026-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_flow_flowexecution_skill_skillexecutionlog_flowstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='tools_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
