# Generated by Django 4.2.3 on 2026-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatsession_tools_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='developer_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='history_limit',
            field=models.IntegerField(default=20, help_text='Number of past messages to include as context (0=no memory)'),
        ),
    ]
